### PR TITLE
Export ConnectionContext constructors

### PR DESCRIPTION
**Pull request by pranaysashank**
Fixes https://github.com/vincenthz/hs-connection/issues/45

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
In general, I would like to export constructors from (new) `Internal` module for backward compatibility.

**Comment by pranaysashank** [comment]
@kazu-yamamoto  How about moving the Types module to exposed modules instead?

**Comment by kazu-yamamoto** [comment]
Sorry for the delay.
I prefer `Internal` because we don't have to take care of backward compatibility.

**Comment by pranaysashank** [comment]
@kazu-yamamoto moved the export to an Internal Module

**Review by kazu-yamamoto — APPROVED** [review]
LGTM

**Comment by kazu-yamamoto** [comment]
Merged and released.
Thank you for your contribution!

**Pull request merged**
